-- Run these updates/additions in your Supabase SQL Editor

-- 1. Organizations Table
create table if not exists public.organizations (
  id bigint generated by default as identity primary key,
  name text not null,
  code text unique,
  clerk_org_id text unique,
  admin_email text,
  status text default 'active',
  plan text default 'starter',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Licenses Table
create table if not exists public.licenses (
  id bigint generated by default as identity primary key,
  organization_id bigint references public.organizations(id) on delete cascade,
  license_key text not null unique,
  status text default 'active',
  expiry_date timestamp with time zone,
  max_users int default 10,
  features jsonb default '{}'::jsonb,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Feature Flags Table
create table if not exists public.feature_flags (
  id bigint generated by default as identity primary key,
  organization_id bigint references public.organizations(id) on delete cascade,
  flag_key text not null,
  is_enabled boolean default false,
  unique(organization_id, flag_key)
);

-- Monitoring Status Table
create table if not exists public.monitoring_status (
  id bigint generated by default as identity primary key,
  service_name text not null,
  status text default 'operational',
  uptime text default '100%',
  latency text default '0ms',
  last_check timestamp with time zone default timezone('utc'::text, now())
);

-- Insert initial values for monitoring
insert into public.monitoring_status (service_name, status, uptime, latency)
values 
('Api Gateway', 'operational', '99.99%', '42ms'),
('Workflow Engine', 'operational', '99.95%', '124ms'),
('Database Cluster', 'operational', '100%', '8ms'),
('Storage Service', 'operational', '99.98%', '15ms');

-- Admin Logs Table
create table if not exists public.admin_logs (
  id bigint generated by default as identity primary key,
  action text not null,
  details text,
  organization_id bigint references public.organizations(id) on delete set null,
  performed_by text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
